### ISSUE TITLE
Example on how to upload configuration to MLC

### ISSUE THREAD

**Issue by jatincc** [stm32duino/LSM6DSOX#2]
I am currently using the following setup:

[NUCLEO-L476RG](https://www.st.com/en/evaluation-tools/nucleo-l476rg.html)
[X-NUCLEO-IKS01A3](https://www.st.com/en/ecosystems/x-nucleo-iks01a3.html)
[STEVAL-MKI197V1](https://www.st.com/en/evaluation-tools/steval-mki197v1.html)

I want to be able to use the ARDUINO IDE to LOAD configuration files (.ucf files) to the LSM6DSOX and use the Machine Learning Core(MLC) feature.

I have tried looking at the Arduino Library code for the [LSM6DSOX](https://github.com/stm32duino/LSM6DSOX) and the [X-NUCLEO-IKS01A3](https://github.com/stm32duino/X-NUCLEO-IKS01A3).
But there are no examples on how to do this.

Can anyone provide a high-level Arduino code that is able to upload configuration file to the MLC and is able to read out the MLC registers and Interrupts?

Edit:
UNICO generates a .h file using the .ucf file.
So arduino code would be using that header file NOT the .ucf file directly.
Like this: [LINK](https://github.com/STMicroelectronics/STMems_Machine_Learning_Core/tree/master/lsm6dsox/Activity%20recognition%20for%20mobile)

I have also put this issue on the [X-NUCLEO-IKS01A3](https://github.com/stm32duino/X-NUCLEO-IKS01A3) Github page as I am not really sure where it belongs.

**Comment by NipunDewthilina** [comment]
Did you findout a way for that
