### ISSUE TITLE
Is there a way to get a time stamp for each measurement in the FIFO buffer?

### ISSUE THREAD

**Issue by LazaroFilm** [stm32duino/LSM6DSOX#21]
I need to know the exact interval between each gyro measurement and check that no values were binned. So I'm thinking of using a FIFO polling, but I would love to know if there's a way to know the exact time between each measurement, independently from my sketch's loop frequency.

**Comment by cparata** [comment]
Hello @LazaroFilm ,
you can tune ODR and BDR values. If they are equal, you should not find binned values and the timestamp between two consecutive values can be calculated as 1/ODR.
Best Regards,
Carlo

**Comment by diplodocuslongus** [comment]
I'd like to come back on this issue: I agree with @cparata that we can obtain the timestamp between two consecutive values  as 1/ODR, but this is not a guaranteed value, this is an ideal value, and no provided by the IMU itself. If samples are missed, the 1/ODR value will lead to offsets in the actual timestamps.

 It would be great to be able to log the actual timestamp, especially, as @LazaroFilm asked, when using the FIFO.

In `lsm6dsox_reg.c` I see there are `lsm6dsox_timestamp_get` and `lsm6dsox_timestamp_raw_get`, can these be used to get the timestamps in FIFO mode?

**Comment by cparata** [comment]
Hello @diplodocuslongus ,
@patricklaf added some APIs to the library to also manage the timestamps of the FIFO; you can find the PR [here](https://github.com/stm32duino/LSM6DSOX/pull/17). Maybe he has also some examples to share that show you how to use these APIs.
Best Regards,
Carlo
