### ISSUE TITLE
Compile failure on esp32-s3: MSBFIRST not defined

### ISSUE THREAD

**Issue by nickjsanders** [stm32duino/LSM6DSOX#24]
Similar to: https://github.com/sparkfun/SparkFun_LSM6DS3_Arduino_Library/issues/6

It seems esp32 arduino libraries define SPI_MSBFIRST rather than MSBFIRST, causing this library to not compile on esp32

Can the following code be added to LSM6DSOXSensor.h?

#ifndef MSBFIRST 
#define MSBFIRST SPI_MSBFIRST
#endif

**Comment by cparata** [comment]
Hello @nickjsanders ,
it makes sense for me.
Best Regards,
Carlo

**Comment by cparata** [comment]
I have released a new version of the library (2.3.4) that includes the fix.
I close the issue.
Best Regards,
Carlo
