### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by pnaybour** [stm32duino/LSM6DSOX#5]
We are evaluating this device for a new product using multiple IMUs for medical applications. An simple example showing how to pull the raw data would be extremely helpful.

**Comment by cparata** [comment]
Hi @pnaybour ,
basically all the IMU 6-axis components work at the same way with stm32duino libraries. You can give a look how LSM6DSO or LSM6DSL are managed respectively in the X-NUCLEO-IKS01A3 HelloWorld sketch (https://github.com/stm32duino/X-NUCLEO-IKS01A3/blob/master/examples/X_NUCLEO_IKS01A3_HelloWorld/X_NUCLEO_IKS01A3_HelloWorld.ino) or in the X-NUCLEO-IKS01A2 HelloWorld sketch (https://github.com/stm32duino/X-NUCLEO-IKS01A2/blob/master/examples/X_NUCLEO_IKS01A2_HelloWorld/X_NUCLEO_IKS01A2_HelloWorld.ino). Basically, you just need to instantiate a I2C or SPI instance and then create an instance of the LSM6DSOX sensor, enable it and get the values. For example, using the I2C bus you will have something like:

LSM6DSOXSensor *AccGyr;
Wire.begin();
AccGyr = new LSM6DSOXSensor (&Wire, LSM6DSOX_I2C_ADD_L);
AccGyr->Enable_X();
AccGyr->Enable_G();

AccGyr->Get_X_Axes(accelerometer);
AccGyr->Get_G_Axes(gyroscope);

In this way you will have the values of the accelerometer expressed in mg and the values of the gyroscope expressed in mdps.
Please, pay attention to use the correct I2C address in the constructor of the LSM6DSOX sensor according your board schematics.
Best Regards,
Carlo
